spring:
  application:
    name: 'fornecedor'
  datasource:
    url: jdbc:postgresql://localhost:5432/alura_fornecedor
    password: anderson
    username: anderson
  jpa:
    hibernate:
      ddl-auto: create   
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
